import { startPage } from '../router.js';
import { mountComposedPage } from './composed.js';

const markup = `
<div class="pagehead"><div><h1 class="pagehead__title">Operations queue</h1><p class="pagehead__sub">Pickering · today · live</p></div>
<div class="pagehead__actions">
<button class="btn btn--quiet btn--icon" title="Customise this page"><svg class="" viewbox="0 0 24 24"><circle cx="12" cy="12" r="3"></circle><path d="M12 2v3m0 14v3M4.2 4.2l2.1 2.1m11.4 11.4 2.1 2.1M2 12h3m14 0h3M4.2 19.8l2.1-2.1M17.7 6.3l2.1-2.1"></path></svg></button>
<button class="btn btn--quiet btn--icon" data-export="" title="Export CSV"><svg class="" viewbox="0 0 24 24"><path d="M12 3v12m0 0 4-4m-4 4-4-4M5 18v3h14v-3"></path></svg></button>
<button class="btn btn--quiet" data-fullscreen="" title="Full screen"><svg class="" viewbox="0 0 24 24"><path d="M4 9V4h5M20 9V4h-5M4 15v5h5M20 15v5h-5"></path></svg><span>Full screen</span></button>
<button class="btn btn--primary" data-open-booking=""><svg viewbox="0 0 24 24"><path d="M12 5v14M5 12h14"></path></svg>Book appointment</button></div></div>
<div class="brief"><span class="brief__ico">AI</span><div class="brief__body"><div class="brief__t">Today's brief · shift focus</div><div class="brief__x">Steady morning, <b>tight 08:00–10:00</b> with 4 movements across 5 docks. One <b>late inbound (MXD-000052)</b> on Dock 4 — chase the carrier. Outbound skids running <b>2× inbound</b>, so stage outbound early. Dock 3 is your pinch point.</div></div><button class="brief__x linkBtn" data-share="">Share with team</button></div>
<div class="kpis kpis--5"><div class="kpi kpi--signal"><span class="kpi__label">Expected</span><span class="kpi__value">4</span></div><div class="kpi kpi--out"><span class="kpi__label">On site</span><span class="kpi__value">2</span></div><div class="kpi kpi--ok"><span class="kpi__label">Completed</span><span class="kpi__value">9</span></div><div class="kpi"><span class="kpi__label">Avg dwell</span><span class="kpi__value">42<span>m</span></span></div><div class="kpi kpi--stop"><span class="kpi__label">Late</span><span class="kpi__value">1</span></div></div>
<div class="split"><div class="panel panel--fill"><div class="panel__head"><div class="tabs"><button aria-pressed="true">All</button><button>Expected</button><button>On site</button><button>Completed</button></div><div class="panel__actions"><span class="sub">16 movements · updated 09:27</span></div></div><div class="panel__scroll"><table class="table"><thead><tr><th>Time</th><th>Reference</th><th>Dock</th><th>Company</th><th>Load</th><th>Status</th><th></th></tr></thead><tbody><tr><td class="data data--strong">07:00</td><td class="data">MXD-000050</td><td class="data">Dock 1</td><td>Guelph transfer</td><td class="data">25 sk</td><td><span class="statusdot">On site</span></td><td><button class="btn btn--quiet btn--sm">Complete</button></td></tr><tr><td class="data data--strong">08:00</td><td class="data">MXD-000051</td><td class="data">Dock 3</td><td>Mississauga</td><td class="data">10 sk</td><td><span class="statusdot">Expected</span></td><td><button class="btn btn--quiet btn--sm">Arrive</button></td></tr><tr><td class="data data--strong">08:30</td><td class="data">MXD-000052</td><td class="data">Dock 4</td><td>—</td><td class="data">8 sk</td><td><span class="statusdot">Late</span></td><td><button class="btn btn--quiet btn--sm">Arrive</button></td></tr><tr><td class="data data--strong">10:00</td><td class="data">MXD-000054</td><td class="data">Dock 2</td><td>Haleon – Oakhill</td><td class="data">6 sk</td><td><span class="statusdot">Expected</span></td><td><button class="btn btn--quiet btn--sm">Arrive</button></td></tr></tbody></table></div></div><div><div class="heat"><h3 class="heat__t">Dock heatmap</h3><div class="heatgrid" id="heat"></div><p class="hint">Darker = busier. Dock 3, 08:00–10:00 is your stress point.</p></div><div class="watch"><h3 class="watch__t">Watch for</h3><div class="watchitem"><span class="wdot"></span><div><b>Late inbound · Dock 4</b>MXD-000052 was due 08:30. Carrier not arrived.</div></div><div class="watchitem"><span class="wdot"></span><div><b>Back-to-back on Dock 3</b>Two movements 08:00 and 08:30 — tight turnaround.</div></div><div class="watchitem"><span class="wdot"></span><div><b>Return-load match</b>Guelph outbound could pair with a Guelph→Pickering inbound.</div></div></div></div></div>`;

startPage({ code: 'queue', async mount(context) { mountComposedPage(context.pageRoot, markup, { code: 'queue', context }); } });
